button:
  jadwal: ':date: Schedules'
  tugas: ':memo: Home Work'
  help: ':wrench: Help'
  back: ':arrow_left: Back'
  data: ':floppy_disk: Data'
  map : ':office: Telkom University Map'
  sholat: ':watch: Prayer Times'
  senin : ':one: Monday'
  selasa : ':two: Tuesday'
  rabu : ':three: Wednesday'
  kamis : ':four: Thursday'
  jumat : ':five: Friday'
  sabtu : ':six: Saturday'
  weather: ':rainbow: Weather'
  cancel: ':negative_squared_cross_mark: Cancel'
  like: ':heart_decoration: I like this bot'
  ujian: ':rocket: UTS/UAS'
  rate:
    like: ":point_up: I've already rated bot"
    later: ":hourglass: I'll rate bot later"
    dislike: ":hankey: I don't want to rate bot"

main :
  notfound : 'Error 404 : Sorry, Data Not Found :disappointed_relieved:'
  
  hi : 'Hello, <%=user.first_name%>, What can I do for you?'
  
  senin : |
    :red_circle: Default Monday Schedules 
    1. 10:30 - 13:30  (A307B)  KECERDASAN BUATAN
    2. 13:30 - 15:30  LABIF-04  JARINGAN KOMPUTER

  selasa : |
    :red_circle: Default Tuesday Schedules 
    1. 07:30 - 09:30  KU3.04.20 DESAIN DAN ANALISIS ALGORITMA
    2. 14:30 - 17:30  KU1.02.13  JARINGAN KOMPUTER
  
  rabu : |
    :red_circle: Default Wednesday Schedules 
    1. 11:30 - 14:30  (A303A) IMPLEMENTASI DAN PENGUJIAN PERANGKAT LUNAK
    2. 14:30 - 17:30  KU3.04.01  INTERAKSI MANUSIA DAN KOMPUTER A

  kamis : |
    :red_circle: Default Thursday Schedules
    1. 06:30 - 08:30  (A208B)  TATA TULIS ILMIAH DAN TEKNIK PRESENTASI
    2. 12:30 - 15:30  (A303B)  KEPROFESIAN INFORMATIKA

  jumat : |
    :red_circle: Default Friday Schedules 
    1. 09:30 - 11:30  (A208A)  DESAIN DAN ANALISIS ALGORITMA
    2. 15:30 - 17:30 LABIF-05  IMPLEMENTASI DAN PENGUJIAN PERANGKAT LUNAK

  sabtu : |
    :red_circle: Default Saturday Schedules 
    1. Free

  tugas : |
    :large_blue_circle: Our Home Work
    1. TUBES IMK 
    2. TUBES IMPAL
    3. TUBES DAA
    4. TUBES JARKOM
    5. TUBES AI

  help : |
    :white_circle: General Commands :
      /hi - say hi and little introduction
      /senin - Get IF-39-08's Monday Course Schedules
      /selasa - Get IF-39-08's Tuesday Course Schedules
      /rabu - Get IF-39-08's Wednesday Course Schedules
      /kamis - Get IF-39-08's Thursday Course Schedules
      /jumat - Get IF-39-08's Friday Course Schedules
      /sabtu - Get IF-39-08's Saturday Course Schedules
      /tugas - Get IF-39-08's Home Work
      /sholat - Get Prayers Time Bandung
      /maptelkom - Get Coordinate of Telkom University
      /data - Get Data of student by type /data yourname
      /weather - Get Forecast for Bandung
      /help - General Information about command

  sholat : |
      :alarm_clock: <%=localtime%>
      Coordinate : <%=latitude%>, <%=longitude%>
      :round_pushpin: Bandung, Indonesia 
      :clock4: Imsak    : <%=waktusholat.imsak%> 
      :clock430: Subuh    : <%=waktusholat.fajr%> 
      :clock530: Sun Rise : <%=waktusholat.sunrise%> 
      :clock12: Zuhur    : <%=waktusholat.dhuhr%> 
      :clock3: Ashar    : <%=waktusholat.asr%> 
      :clock6: Maghrib  : <%=waktusholat.maghrib%> 
      :clock7: Isya     : <%=waktusholat.isha%> 
    
  info : |
    :heavy_check_mark: Choose Schedule 


  weather : |
    :round_pushpin: Bandung, Indonesia
    :telescope: Currently Weather Conditions:
    ---- <%=statuss%> ----
    Temperature : <%=temperatures%> °C
    Dew Point : <%=dewpoint%> °C
    Humidity : <%=humiditys%> %
    Cloud Cover in Sky : <%=sky%> %
    Wind Speed : <%=winds%> miles/hours
    Wind Direction : <%=windbear%> °
    Atmospheric Pressure : <%=pressure%> hPa
    Area Density of Ozone : <%=ozone%> DU

    :telescope: Tommorow Prediction:
    <%=hourly%>

    :telescope: Weekly Prediction:  
    <%=today%>

  ujian : |
    -- Nothing --

