button:
  jadwal: ':date: Schedules'
  tugas: ':memo: Home Work'
  help: ':wrench: Help'
  back: ':arrow_left: Back'
  data: ':floppy_disk: Data'
  map : ':office: Telkom University Map'
  sholat: ':watch: Prayer Times'
  senin : ':one: Monday'
  selasa : ':two: Tuesday'
  rabu : ':three: Wednesday'
  kamis : ':four: Thursday'
  jumat : ':five: Friday'
  sabtu : ':six: Saturday'
  remove: ':x: Delete'
  cancel: ':negative_squared_cross_mark: Cancel'
  like: ':heart_decoration: I like this bot'
  rate:
    like: ":point_up: I've already rated bot"
    later: ":hourglass: I'll rate bot later"
    dislike: ":hankey: I don't want to rate bot"

main :
  notfound : 'Error 404 : Sorry, Data Not Found :disappointed_relieved:'
  
  hi : 'Hello, <%=user.first_name%>, What can I do for you?'
  
  senin : |
    :red_circle: Default Monday Schedules 
    1. Example1
    2. Example2
    3. Example3

  selasa : |
    :red_circle: Default Tuesday Schedules 
    1. Example1
    2. Example2
    3. Example3
  
  rabu : |
    :red_circle: Default Wednesday Schedules 
    1. Example1
    2. Example2
    3. Example3

  kamis : |
    :red_circle: Default Thursday Schedules
    1. Example1
    2. Example2
    3. Example3

  jumat : |
    :red_circle: Default Friday Schedules 
    1. Example1
    2. Example2
    3. Example3

  sabtu : |
    :red_circle: Default Saturday Schedules 
    1. Example1
    2. Example2
    3. Example3

  tugas : |
    :large_blue_circle: Our Home Work
    1. Example1
    2. Example2
    3. Example3

  help : |
    :white_circle: General Commands :
      /hi - say hi and little introduction
      /senin - Get IF-39-08's Monday Course Schedules
      /selasa - Get IF-39-08's Tuesday Course Schedules
      /rabu - Get IF-39-08's Wednesday Course Schedules
      /kamis - Get IF-39-08's Thursday Course Schedules
      /jumat - Get IF-39-08's Friday Course Schedules
      /sabtu - Get IF-39-08's Saturday Course Schedules
      /tugas - Get IF-39-08's Home Work
      /sholat - Get Prayers Time Bandung
      /maptelkom - Get Coordinate of Telkom University
      /data - Get Data of student by type /data yourname
      /help - General Information about command

  sholat : |
      :alarm_clock: <%=localtime%>
      Coordinate : <%=latitude%>, <%=longitude%>
      :round_pushpin: Bandung, Indonesia 
      :clock4: Imsak    : <%=waktusholat.imsak%> 
      :clock430: Subuh    : <%=waktusholat.fajr%> 
      :clock530: Sun Rise : <%=waktusholat.sunrise%> 
      :clock12: Zuhur    : <%=waktusholat.dhuhr%> 
      :clock3: Ashar    : <%=waktusholat.asr%> 
      :clock6: Maghrib  : <%=waktusholat.maghrib%> 
      :clock7: Isya     : <%=waktusholat.isha%> 

